icgc:
  dcc:
    submission:
      ega:
        metadata:
          ftp:
            host:
            user:
            password:
            path:
          cron:
            data: 0 0 9,21 * * ?
            clean: 0 0 0 ? * 2 ?
          postgresql:
            host: localhost
            database:
            user: postgres
            password:
            viewName: view_ega_sample_mapping